# Generated by Django 2.0.7 on 2018-07-17 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_user_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_img_url',
            new_name='pic',
        ),
    ]
