# Generated by Django 2.0.7 on 2018-07-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField(unique=True)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField(unique=True)),
                ('course', models.IntegerField()),
                ('itinerary', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='study',
            name='subject',
            field=models.ManyToManyField(to='academics.Subject'),
        ),
    ]
