# Generated by Django 2.0.7 on 2018-07-21 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_references'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='references',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='references',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.References'),
            preserve_default=False,
        ),
    ]
