# Generated by Django 2.0.7 on 2018-07-21 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_auto_20180721_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='references',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='academics.References'),
        ),
    ]
