# Generated by Django 2.0.7 on 2018-07-21 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_auto_20180721_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='references',
        ),
        migrations.AddField(
            model_name='references',
            name='references',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.Subject'),
        ),
    ]
